// Auto-generated user library (Tidal + Spotify)
const KNOWN_PAIRS = new Set([
  "1001 Est Crémazie|||1001 Est Crémazie",
  "1619 Bad Ass Band|||1619 Bad Ass Band (Digitally Remastered)",
  "24 Carat Black|||Ghetto: Misfortune's Wealth",
  "A Song For You, Holan|||Home",
  "ABC, Halina Frackowiak|||Grupa ABC Andrzeja Nebeskiego",
  "AJ McQueen, Londrelle|||SIT YUH SELF DOWN",
  "Aaron Frazer|||Bring You A Ring",
  "Adrian Younge|||Adrian Younge presents Something About April III",
  "Airto Moreira|||Touching You, Touching Me",
  "Akira Ishikawa & Count Buffaloes|||African Rock",
  "Aktuala|||La terra",
  "Al Stewart|||Running Man - Introducing... Al Stewart",
  "Alain Bellaïche|||Late Night Tales: Floating Points",
  "Alain Goraguer|||La Planète Sauvage (Original Motion Picture Soundtrack)",
  "Alan Lorber Orchestra|||The Lotus Palace",
  "Alan Parker\t\"album\": \"9-10-Out\"",
  "Alejandro Jodorowsky|||The Holy Mountain (Original Motion Picture Soundtrack)",
  "Alessandro Alessandroni|||Panoramic Feelings (Mellow Carefree Lounge Music)",
  "Alessandro Alessandroni|||Romantic Beats",
  "Alessandro Blonksteiner|||A mezzanotte va la ronda del piacere (Original Motion Picture Soundtrack)",
  "Alessandro Blonksteiner|||Afrika Erotika (Original Soundtrack)",
  "Alfonso Zenga, Paolo Gatti|||Sensi caldi (Original Soundtrack)",
  "Alfred Newman|||Airport (Original Soundtrack)",
  "Alice Coltrane\t\"album\": \"Huntington Ashram Monastery\"",
  "Allan Holdsworth\t\"album\": \"Wardenclyffe Tower (Remastered)\"",
  "Allan Wachs\t\"album\": \"Mountain Roads & City Streets\"",
  "Alquin|||The Mountain Queen",
  "Amado Maita|||Amado Maita",
  "Amanda Whiting, Chip Wickham|||The Liminality of Her",
  "Anacole Daalderop, Marc Eric Laine\t\"album\": \"Electro Jazz\"",
  "Anaïs Mitchell|||Hymns for the Exiled",
  "Andrae Crouch, Disciples|||Classic Gold: Take Me Back: Andrae Crouch and the Disciples",
  "Andre Kostelanetz & His Orchestra|||I Wish You Love",
  "Andre Tschaskowski|||Emotionally",
  "Andre Tschaskowski|||Suspense and Danger",
  "Andrew Hill|||Pax",
  "André Popp|||Mon cinéma à moi",
  "Andy Williams|||16 Biggest Hits",
  "Angel 'Pocho' Gatti Orchestra|||The best of",
  "Angel 'Pocho' Gatti Orchestra|||Turbomusic (Formula 1 Races - Vintage Lounge Funk Jazz)",
  "Angel Pocho Gatti e la sua grande orchestra|||Amore e musica",
  "Angela Bofill|||Angie (Expanded Edition)",
  "Antonio Adolfo|||Feito Em Casa",
  "Antony and the Johnsons, ANOHNI|||The Crying Light",
  "Antón García Abril|||El Hombre y la Tierra (Banda Sonora Original de la Serie de TVE)",
  "Apollo Brown, Bronze Nazareth|||Funeral For A Dream",
  "Aquarian Dream|||Fantasy",
  "Ara Tokatlian, Milcho Leviev|||In Memoriam",
  "Arco Iris|||Sudamérica o el Regreso a la Aurora",
  "Areski Belkacem|||Un beau matin",
  "Armand Hammer, The Alchemist, billy woods, E L U C I D, Silka, Cleo Reed|||Calypso Gene (feat. Silka & Cleo Reed)",
  "Armando Trovajoli|||L'anatra all'arancia (Original Motion Picture Soundtrack)",
  "Ash Ra Tempel, Manuel Göttsching|||Starring Rosi",
  "Astrud Gilberto\t\"album\": \"The Astrud Gilberto Album\"",
  "Augusto Martelli|||Black Sound From White People",
  "Augusto Martelli|||The Real Mc Coy",
  "Azymuth\t\"album\": \"Águia não come mosca\"",
  "Azymuth|||Demos (1973-1975), Vol. 1 & 2",
  "Azymuth|||Zé e Paraná",
  "BADBADNOTGOOD, Charlotte Day Wilson|||IV",
  "Balla Et Ses Balladins|||The Syliphone Years",
  "Bastien Keb, Claudia Kane|||The Killing of Eugene Peeps",
  "Bemibem\t\"album\": \"Bemowe frazy\"",
  "Bengt Hallberg|||Collaboration",
  "Benjamim Taubkin\t\"album\": \"Piano Masters Vol 1\"",
  "Benny The Butcher, Black Thought|||The Plugs I Met",
  "Betty Missiego|||Lo Mejor de Betty Missiego",
  "Beverly Glenn-Copeland|||Primal Prayer",
  "Beverly Glenn-Copeland|||Transmissions: The Music Of Beverly Glenn-Copeland",
  "Big Band Katowice|||Music for My Friends (Polish Jazz vol. 52)",
  "Bill Evans\t\"album\": \"Waltz For Debby (Original Jazz Classics Remaster 2010)\"",
  "Bill Evans Trio|||Waltz For Debby (Original Jazz Classics Remaster 2010)",
  "Bill Fay|||Still Some Light: Part 1 (Piano, Guitar, Bass & Drums 1970-1971)",
  "Billy Strayhorn|||The Peaceful Side Of Jazz",
  "Bits & Noise|||Deep Sleep Brown Noise",
  "Bizarrap, Quevedo|||Quevedo: Bzrp Music Sessions, Vol. 52/66",
  "Bjørn Alterhaug|||A Ballad",
  "Black Savage|||Black Savage",
  "Black Thought\t\"album\": \"Cheat Codes\"",
  "Blu, August Fanon, Wyldeflowher, Geminelle, YaH-Ra, Lexus, Noveliss|||Forty",
  "Blu, YaH-Ra, MED, Thurz|||We Bang Remixes",
  "Blue Earth Sound|||Cicero Nights",
  "BlueskyBeatz|||What I Hear",
  "Bobby Hutcherson|||Linger Lane",
  "Bohemian Vendetta|||Bohemian Vendetta",
  "Boillat Thérace Quintet, Benny Bailey|||My Greatest Love",
  "Bonnie Raitt|||Bonnie Raitt (2008 Remaster)",
  "Brandon Coleman|||Resistance",
  "Bread|||On the Waters",
  "Brief Encounter|||We Want to Play",
  "Broadcast|||The Noise Made By People",
  "Brodowski String Quartet & Dave Kane & Marius Neset & Olavi Louhivuori & Dave Stapleton\t\"album\": \"Flight\"",
  "Bruce Campbell|||Bmlp 073",
  "Bruno Battisti D'Amario\t\"album\": \"Chitarre Folk\"",
  "Bruno Nicolai\t\"album\": \"Genti Di Rispetto/ Spasmo\"",
  "Bruno Nicolai|||Eleonora (Original TV Series Soundtrack)",
  "Bruno Nicolai|||Sexy Sports: Vinyl Oddities & Break Beats 1960-1984, Vol. 1",
  "Burt Bacharach|||Reach Out",
  "Butch Dawson|||SANTI",
  "Cal Tjader|||Agua Dulce",
  "Calvin Keys|||Full Court Press",
  "Caravan|||Blind Dog at St. Dunstans (Remastered)",
  "Caravan|||The World Is Yours – The Anthology 1968-1976",
  "Carca|||A un Millón de Años Blues",
  "Cassiano|||Imagem e Som",
  "Catalyst|||The Funkiest Band You Never Heard",
  "Caterina Valente|||Caterina Valente e i suoi più grandi successi",
  "Catherine Howe\t\"album\": \"What a Beautiful Place\"",
  "Catherine Howe|||What a Beautiful Place",
  "Catherine McKinnon|||Something Old, Something New",
  "Cecilia|||Un Ramito De Violetas",
  "Cesar Camargo Mariano|||São Paulo - Brasil",
  "Cesare Andrea Bixio, Luciano Pavarotti, Andrea Griminelli, Henry Mancini|||Mamma",
  "Charles Lloyd|||Pathless Path",
  "Charly García\t\"album\": \"Piano Bar\"",
  "Chassol|||I figli morti",
  "Chester Watson\t\"album\": \"Tin Wooki\"",
  "Chester Watson, Dr. Josephine OlaTomi Soboyejo|||Continuum",
  "Chet Baker Quartet, Russ Freeman|||Chet Baker Quartet Featuring Russ Freeman (Expanded Edition)",
  "Chico Hamilton|||The Master",
  "Chief Adjuah|||Stretch Music",
  "Ciccada\t\"album\": \"The Finest of Miracles\"",
  "Clare Fischer|||Songs for Rainy Day Lovers",
  "Claudette Soares|||De Tanto Amor",
  "Claudine Longet|||Claudine",
  "Clearlight|||Symphony II",
  "Clever Austin\t\"album\": \"Headshell Hideaway, Vol. 2\"",
  "Clipse\t\"album\": \"Let God Sort Em Out\"",
  "Clipse, COLORS|||Ace Trumpets - A COLORS SHOW",
  "Clipse, Pusha T, Malice|||Let God Sort Em Out",
  "Collettivo Immaginario, Maylee Todd, Tommaso Cappellato, Alberto Lincetto, Nicolò Masetto|||Alberoni",
  "Corey Bernhard|||A Blessed Leap Into Eternity",
  "Cos|||Viva Boma",
  "Courtial With Errol Knowles\t\"album\": \"Don't You Think It's Time\"",
  "Cozy Fr|||Supreme Flyentele",
  "Cynthia Schloss|||Ready and Waiting in Memory",
  "Céline Dessberg|||Hödöö",
  "DJ Gruff|||O tutto o niente",
  "DJ Shocca, Madbuddy|||Sacrosanto",
  "Dan Fogelberg\t\"album\": \"Twin Sons Of Different Mothers\"",
  "Danger Mouse, Black Thought, MF DOOM|||Cheat Codes",
  "Daniele Patucchi, Nora Orlandi, 4 + 4 Di Nora Orlandi|||Il sesso della strega (Original Soundtrack)",
  "Daniele Patucchi, Nora Orlandi|||Il sesso della strega (Original Soundtrack)",
  "Danny O'Keefe|||O'Keefe",
  "Dave Bixby|||Ode To Quetzalcoatl",
  "David Axelrod|||Messiah",
  "David Axelrod|||Seriously Deep",
  "David Axelrod|||Song Of Innocence",
  "David Lindup|||Kpm 1000 Series: Dramatic Background",
  "David Lindup|||Kpm 1000 Series: Gentle Sounds - Volume 3",
  "David Sanborn|||Sanborn",
  "Daylan Gideon\t\"album\": \"MOVE MOUNTAINS\"",
  "Deitrich Johnson|||REDLIGHT VIBES VOLUME 1",
  "Del Jones' Postive Vibes|||Court Is Closed",
  "Deodato|||Bis Bossa Nova - Um Banquinho E Um Violão",
  "Di Melo|||Di Melo",
  "Dirty Art Club\t\"album\": \"Gardens\"",
  "Dirty Art Club|||Basement Seance",
  "Dirty Art Club|||Heavy Starch",
  "Diz|||ULTRA.VIOLET",
  "Diz|||the way forward is not the way home",
  "Dolly Parton|||The Essential Dolly Parton",
  "Dom Salvador, Edison Machado|||Tristeza",
  "Dominique Guiot|||L'Univers De La Mer",
  "Don Beto|||Nossa Imaginação",
  "Don beto\t\"album\": \"Nossa Imaginação\"",
  "Donald Byrd\t\"album\": \"Royal Flush\"",
  "Donald Byrd|||Street Lady",
  "Doris Monteiro\t\"album\": \"Doris Monteiro\"",
  "Doug Hammond, David Durrah|||Reflections In The Sea Of Nurnen",
  "Doug Lucas|||Niara",
  "Dough Networkz, Young Roddy, Jameel Na'im X, King Akeem|||Dis For The Project (Side A)",
  "Dr. Lonnie Smith|||Finger Lickin' Good",
  "Dr. Samuel J. Hoffman\t\"album\": \"Music For Peace Of Mind: Featuring The Theremin With Orchestra\"",
  "Dr. Yen Lo\t\"album\": \"Days With Dr. Yen Lo\"",
  "Duke Pearson|||How Insensitive",
  "Durand Jones & The Indications\t\"album\": \"American Love Call\"",
  "Dzamble|||Wołanie o słońce nad światem",
  "East Of Eden|||Snafu",
  "Eddy Senay|||Hot Thang",
  "Eduardo Mateo, Jorge Trasante|||Mateo y Trasante",
  "Egberto Gismonti|||Sonho 70",
  "Elis Regina\t\"album\": \"Essa Mulher\"",
  "Eloy|||Power And The Passion",
  "Elton John\t\"album\": \"Honky Chateau\"",
  "Eminem, DMX, Obie Trice|||Cradle 2 The Grave",
  "Eminencee|||Four Seasons",
  "Emma-Jean Thackray|||Yellow",
  "Ennio Morricone\t\"album\": \"Il gatto (Original Motion Picture Soundtrack)\"",
  "Ennio Morricone\t\"album\": \"Le foto proibite di una signora per bene (Original Motion Picture Soundtrack)\"",
  "Ennio Morricone\t\"album\": \"Svegliati e uccidi - Wake Up and Die (Original Motion Picture Soundtrack) (Remastered)\"",
  "Ennio Morricone e i Cantori Moderni di Alessandroni|||Vergogna schifosi (Original Motion Picture Soundtrack)",
  "Ennio Morricone\\, Edda e i Cantori Moderni di Alessandroni|||Vergogna schifosi (Original Motion Picture Soundtrack)",
  "Ennio Morricone|||L'assoluto naturale (Original Motion Picture Soundtrack)",
  "Ennio Morricone|||La cosa buffa",
  "Ennio Morricone|||Le foto proibite di una signora per bene (Original Motion Picture Soundtrack)",
  "Enrico Rava, Fred Hersch|||The Song Is You",
  "Enrico Rava|||Katcharpari",
  "Enrico Simonetti, Orquestra Rge|||Swedish Rhapsody",
  "Enrico Simonetti|||Grazie nonna (Colonna sonora del film \"\"Grazie nonna\"\")",
  "Enrico Simonetti|||I colori del piano",
  "Enrico Simonetti|||Il Magnate (Original Motion Picture Soundtrack)",
  "Enrico Simonetti|||Verginita' (Original Motion Picture Soundtrack)",
  "Erick the Architect, Loyle Carner, FARR|||Let It Go",
  "Ernan Roch|||La Onda Pesada",
  "Erni Clark|||By the Grace of God, I Am",
  "Ernie Hines|||Electrified",
  "Ethel Azama|||Exotic Dreams",
  "Fabio Frizzi\t\"album\": \"… e tu vivrai nel terrore - L'Aldilà (Original Motion Picture Soundtrack)\"",
  "Fabri Fibra|||Caos",
  "Fafá de Belém|||Tamba-Tajá",
  "Fafá de Belém|||Água",
  "Fantastic Four|||Alvin Stone (The Birth And Death Of A Gangster) / Night People",
  "Far East Family Band|||Parallel World",
  "Filippo Trecca|||Le città del mondo (Colonna sonora del film TV \"\"Le città del mondo\"\")",
  "Finch|||Galleons of Passion (expanded & remastered)",
  "Flako, Miguel Atwood-Ferguson|||12 O'Clock Shadow",
  "Floating Points, Pharoah Sanders, London Symphony Orchestra|||Promises",
  "Focus|||Mother Focus",
  "Focus|||The Best Of Focus / Hocus Pocus",
  "Francis Hime|||Francis Hime",
  "Francis Hime|||Passaredo",
  "Francis Lai|||La course du lièvre à travers les champs (Bande originale du film)",
  "Francis Lai|||Un homme et une femme (Original Motion Picture Soundtrack)",
  "Francisco Mário|||Revolta Dos Palhaços",
  "Franco Potenza|||Down in the city N.1",
  "Frank McDonald, Chris Rae, De Wolfe Music|||Mean & Dirty",
  "Frank Pole, TEO MANDRELLI, Jordan Grace|||Someone Like You",
  "Françoise Hardy|||Françoise (La maison où j'ai grandi)",
  "Freddie Gibbs, The Alchemist|||Alfredo 2",
  "Freundeskreis, Max Herre, Don Philippe, DJ Friction|||Quadratur des Kreises",
  "Fuubutsushi|||Fuubutsushi",
  "G3 Victory|||Against All Odds",
  "GIMS|||Ceinture noire",
  "GIVĒON\t\"album\": \"BELOVED\"",
  "GIVĒON|||BELOVED",
  "GZA, Ghostface Killah, Streetlife|||Legend Of The Liquid Sword",
  "Gabe 'Nandez, Thomas Maggart|||False Profit",
  "Garland Green\t\"album\": \"Love Is What We Came Here For (Expanded Edition)\"",
  "Gary Burton|||Good Vibes",
  "Gene Harris & The Three Sounds|||Elegant Soul (Reissue)",
  "Gene Harris|||In A Special Way",
  "George Benson|||Bad Benson",
  "George Otsuka|||Loving You George",
  "George Saxon|||A Saxophone Around The World - 9a Raccolta",
  "Gerardo Frisina|||Ad Lib",
  "Giane|||Suavemente",
  "Gianna|||Cocaina / Tango Svizzero",
  "Gianni Brezzo, Simone Alessandrini|||Amoria",
  "Gianni Brezzo|||Tutto Passa",
  "Gianni Fallabrino e la sua orchestra|||Music for Sensations",
  "Gianni Ferrio|||Appuntamento in Riviera (Original Soundtrack)",
  "Gianni Ferrio|||Il vizio di famiglia (Colonna sonora originale del film)",
  "Gianni Ferrio|||L'uomo senza memoria (Original Motion Picture Soundtrack) [Remastered]",
  "Gianni Ferrio|||La calandria (Original Motion Picture Soundtrack)",
  "Gianni Ferrio|||La morte accarezza a mezzanotte (Original Motion Picture Soundtrack)",
  "Gianni Marchetti, 4 + 4 Di Nora Orlandi|||Il magnifico Tony Carrera (Official Motion Picture Soundtrack)",
  "Gianni Marchetti|||Solstitium",
  "Gilberto Gil|||Refavela",
  "Gilgamesh|||Gilgamesh",
  "Gino Vannelli|||Crazy Life",
  "Gino Vannelli|||Powerful People",
  "Gioielli SEXtet|||Late Night Greaters",
  "Gionni Gioielli\t\"album\": \"5 bambole per la luna d'agosto\"",
  "Gionni Gioielli\t\"album\": \"Mediterraneo\"",
  "Gionni Gioielli\t\"album\": \"Travolti da un insolito destino nell'azzurro mare dell'estate\"",
  "Gionni Gioielli, MxRxGxA|||Janet Agren, pt. 3",
  "Giorgio Gaslini|||Rivelazioni di un maniaco sessuale a capo della squadra mobile (Original Motion Picture Soundtrack)",
  "Glen Campbell\t\"album\": \"By The Time I Get To Phoenix (Remastered)\"",
  "Glen Campbell|||Wichita Lineman (Remastered)",
  "Gloria Ann Taylor|||Love is a Hurtin' Thing",
  "Gotts Street Park\t\"album\": \"On The Inside\"",
  "Grover Washington\\, Jr.|||A Secret Place",
  "Grover Washington\\, Jr.|||Feels So Good",
  "Grover Washington\\, Jr.|||Paradise",
  "Grupa Organowa Krzysztofa Sadowskiego, Krzysztof Sadowski|||Na kosmodromie",
  "Guilherme Coutinho, Grupo Stalo|||Guilherme Coutinho E O Grupo Stalo",
  "Gustavo Pena - El Príncipe|||Buraco Incivilizado I y II. 1984/86",
  "Guy Skornik|||Pour Pauwels",
  "Gwen McCrae|||For Your Love",
  "Hadley Caliman|||Hadley Caliman",
  "Hailu Mergia, The Walias|||Tezeta",
  "Hareton Salvanini|||S.P/73",
  "Harold Melvin & The Blue Notes\t\"album\": \"Satisfaction Guaranteed - The Best Of Harold Melvin & The Bluenotes\"",
  "Harvey Averne|||The Harvey Averne Dozen",
  "Harvey Mandel|||Essential Guitar Masters",
  "Hatfield & The North|||Hatfield And The North",
  "Hatfield & The North|||The Rotters Club",
  "Heitor Villa-Lobos, Norbert Kraft|||Villa-Lobos: Music for Solo Guitar (Complete)",
  "Hemlata, Ravindra Jain|||Ankhiyon Ke Jharokhon Se (Original Motion Picture Soundtrack)",
  "Henry Mancini\t\"album\": \"Me, Natalie (Original Soundtrack Recording)\"",
  "Henry Mancini\t\"album\": \"The Pink Panther - Original Soundtrack\"",
  "Henry Mancini|||The Party",
  "Heraldo Do Monte|||Cordas Vivas",
  "Herb Alpert & The Tijuana Brass|||You Smile - The Song Begins",
  "Hermeto Pascoal|||Zabumbe-Bum-A (Remasterizado)",
  "Hikaru Hayashi\t\"album\": \"The Naked Island (L'ile nue) [Original Motion Picture Soundtrack]\"",
  "Hikaru Hayashi|||The Naked Island (L'ile nue) [Original Motion Picture Soundtrack]",
  "Hoover|||Sad About the Times",
  "Huntertones\t\"album\": \"Time to Play\"",
  "I Gres|||I Gres",
  "I Marc 4\t\"album\": \"S.M. 2001\"",
  "IDK, Cordae|||PRiNCE GEORGE",
  "Ian Carr|||Belladonna",
  "Ike White|||Changin' Times",
  "Inner Dialogue|||Inner Dialogue (Remastered)",
  "Ivan Lins|||Modo Livre",
  "Ivan Lins|||Somos Todos Iguais Nesta Noite",
  "J Dilla|||Jay Love Japan",
  "J.J. Johnson, Bill Withers|||Man and Boy",
  "JID, Westside Gunn|||God Does Like Ugly",
  "JID|||God Does Like Ugly",
  "Jackie Moore|||Sweet Charlie Babe",
  "Jackson C. Frank|||American Troubadour",
  "Jacques Brel, Jean Claudric, Le Grand Orchestre De RTL|||Le monde symphonique de Jacques Brel",
  "Jacula|||Tardo Pede In Magiam Versus (35th Anniversary Ed.)",
  "Jade Warrior|||Jade Warrior",
  "Jameel Na'im X|||FOR MY KID'S KIDS",
  "Jameel Na'im X|||ITS NOT THAT SIMPLE",
  "Jan Akkerman|||Jan Akkerman 3",
  "Jan Jelinek|||Loop-Finding-Jazz-Records",
  "Jane Olivor|||Stay The Night",
  "Jane Olivor|||The Best side Of Goodbye",
  "Janko Nilovic|||Classical Phases",
  "Janko Nilovic|||Pop Impressions (Remastered)",
  "Janko Nilovic|||Super America (Remastered)",
  "Jasmine Myra|||Horizons",
  "Jason Joshua & The Beholders\t\"album\": \"Rose Gold\"",
  "Javad Maroufi, Amir Farid|||Amir Farid plays Javad Maroufi",
  "Jean-Luc Ponty|||Cosmic Messenger",
  "Jean-Pierre Mirouze|||Le mariage collectif (Original Motion Picture Soundtrack)",
  "Jeff Alexander|||Late Night Tales: Air",
  "Jeff Beck|||Wired",
  "Jeri Southern\t\"album\": \"You Better Go Now\"",
  "Jerzy Milian, Orkiestra Rozrywkowa PRiTV w Katowicach|||Nagrania 1977",
  "Jim Croce|||You Don't Mess Around With Jim",
  "Jimmie D|||No Love",
  "Joan Brooks|||The Long and Winding Road",
  "Joe Armon-Jones\t\"album\": \"Idiom\"",
  "Joe Armon-Jones\t\"album\": \"Turn to Clear View\"",
  "Joe Henderson|||In Pursuit Of Blackness/Black Is The Color",
  "Joe Sample|||Rainbow Seeker",
  "Joey Bada$$|||Lonely At The Top",
  "John Cameron\t\"album\": \"Kes (Original Soundtrack Music)\"",
  "John Edwards|||Careful Man",
  "John Jacob Niles, Luciano Berio, Cathy Berberian, Juilliard Ensemble|||Berio: Recital I For Cathy & Folk Songs",
  "John Lennon\t\"album\": \"Rock 'N' Roll\"",
  "John Lennon|||Walls And Bridges",
  "John Stammers|||John Stammers",
  "John Stammers|||Waiting Around",
  "Johnny \"\"Hammond\"\" Smith|||Gears",
  "Johnny Andrews & The Enjoyments|||If I Lost Your Love",
  "Johnny Harris|||Movements",
  "Johnny Lytle|||People & Love (Remastered 2023)",
  "Johnny Mathis|||The Essential Johnny Mathis",
  "Jonny Teupen|||Harpadelic",
  "Jordi Sabatés|||Ocells del Més Enllà",
  "Jose Mauro|||Obnoxius",
  "Jose Partida|||Enlightened Man",
  "Joshua, Shablo|||COLD",
  "José Feliciano|||Angela",
  "José Luis Perales|||Para vosotros canto",
  "João Bosco\t\"album\": \"Comissão De Frente\"",
  "João Moraes, Ricardo Santoro|||Um rancho nas nuvens (A música de Antônio Carlos Jobim)",
  "Juan Carlos Calderón, Fernando Lopez|||Juan Carlos Calderón Y Su Taller de Música (Remasterizado 2021)",
  "Juarez Moreira|||Juá",
  "Judee Sill\t\"album\": \"Heart Food\"",
  "Judy Collins|||Judith",
  "Judy Roberts|||Nights in Brazil",
  "Julie London\t\"album\": \"Ultra-Lounge: Fuzzy Retail Sampler\"",
  "K. L. Saigal|||Hits Of K L Saigal Vol 1",
  "Kadhja Bonet|||Remember the Rain",
  "Kamaal Williams, Miguel Atwood-Ferguson|||Wu Hen",
  "Kamaal Williams|||Stings",
  "Kamasi Washington|||Becoming (Music from the Netflix Original Documentary)",
  "Kanye West|||The Life Of Pablo",
  "Kassi Valazza|||Kassi Valazza Knows Nothing",
  "Kathryn Moses|||Music In My Heart",
  "Ka|||The Thief Next to Jesus",
  "Keith Papworth, De Wolfe Music|||Hard Hitter",
  "Kenny Wheeler\t\"album\": \"Angel Song\"",
  "Kha'lil|||DEATH OF TAME",
  "Kid Howl, DDS Pluto|||LACRIMEeSALE",
  "King Curtis|||King Size Soul",
  "KingiKeem, Dough Networkz, Jameel Na'im X, Wildlifejaydot|||If God Say the Same",
  "KingiKeem, Dough Networkz|||If God Say the Same",
  "KingiKeem, Jameel Na'im X, Ren Gettz|||For the Love of Money",
  "Kit Sebastian|||Enkaz",
  "L.N. Chancler, The Chocolate Jam Co.|||The Spread of the Future",
  "LIBERATO|||LIBERATO",
  "La Mont Zeno Theatre|||Black Fairy",
  "Labi Siffre, Kevin W. Smith|||So Strong",
  "Lallo Gori|||La morte scende leggera (Original Motion Picture Soundtrack)",
  "Lalo Schifrin|||Dirty Harry",
  "Lani Hall|||Sun Down Lady",
  "Larry Nozero, Dennis Tini|||Time",
  "Laura Nyro|||Nested",
  "Laurie Styvers|||Gemini Girl: The Complete Hush Recordings",
  "Laurie Styvers|||Let Me Comfort You: The Hush Rarities",
  "Lee Hazlewood|||13",
  "Leko, STRAIGHT OUTTA VAULT, Yandhi|||Brighten Your Day",
  "Leland Whitty|||Anyhow",
  "Les & Larry Elgart|||Nashville Country Piano",
  "Les McCann|||Layers",
  "Les McCann|||Talk To The People",
  "Life|||Life b/w Cu Cu Ru Cu Cu Paloma",
  "Linda Jones|||The Greatest Hits",
  "Lionel Richie|||Can't Slow Down",
  "Litto Nebbia|||Cosas Que No Quieren Morir (Vol. 1 & 2)",
  "Litto Nebbia|||Toda Canción Será Plegaria / The Naked Word",
  "Liv.e|||Couldn't Wait to Tell You...",
  "Loaded Honey, Lydia Kitto, J Lloyd|||Love Made Trees",
  "Lolita|||Mis Recuerdos",
  "Lonnie Liston Smith\t\"album\": \"Expansions\"",
  "Lord Apex, Dash green|||Smoke Sessions, Vol. 1",
  "Lord Apex|||Smoke Sessions 3",
  "Lorenzo Morresi, Tenderlonious|||Scoglio Rosso / Chiaia di Luna",
  "Los Abuelos De La Nada|||Los Abuelos De La Nada",
  "Lou Ragland\t\"album\": \"Lou Ragland and the Great Lakes Orchestra\"",
  "Lou Ragland|||Is The Conveyor \"\"Understand Each Other\"",
  "Lucina\t\"album\": \"Luli & Lucinha\"",
  "Lucy Steymel|||Goodbye to Grey",
  "Luis Alberto Spinetta\t\"album\": \"Kamikaze\"",
  "Luis Alberto Spinetta|||A 18' Del Sol",
  "Luis Alberto Spinetta|||Only Love Can Sustain",
  "Luis Bacalov, Ann Margret|||Rebus - Appointment in Beirut (Original Motion Picture Soundtrack)",
  "Lupita D'Alessio|||Solo Soy Una Mujer (2025 Remastered)",
  "Luther Ingram\t\"album\": \"Luther Ingram Refreshed\"",
  "Lynda Dawn|||11th Hour",
  "MAVI, Smino|||Potluck",
  "MC Solaar|||Prose combat",
  "MIKE, Wiki, The Alchemist|||Faith Is A Rock",
  "Mach-Hommy\t\"album\": \"#RICHAXXHAITIAN\"",
  "Mach-Hommy, Melanie Charles|||Pray For Haiti",
  "Mach-Hommy, Sam Gendel|||#RICHAXXHAITIAN",
  "Mahavishnu Orchestra\t\"album\": \"The Essential Mahavishnu Orchestra with John McLaughlin (with John McLaughlin)\"",
  "Mahavishnu Orchestra|||Visions of the Emerald Beyond",
  "Maha|||Orkos (Habibi Funk 020)",
  "Maki Asakawa|||シングル・コレクション",
  "Malcolm Edmonstone Trio|||It All Begins With You",
  "Mano De Santo\t\"album\": \"El folklore de cada uno\"",
  "Manoella Torres|||Abrazame",
  "Manolo Otero|||Manolo Otero (Remastered 2015)",
  "Maranatha! Music|||Praise 1 - The Praise Album",
  "Marcos Valle|||Vento Sul",
  "Marcos Valle|||Viola Enluarada",
  "Margarita Vilcāne, Nora Bumbiere, Raimonds Pauls|||Tik dzintars vien",
  "Margie Joseph|||Sweet Surrender",
  "Maria Medina|||Lo Mejor de Mí...",
  "Mariah Carey|||Music Box",
  "Mariani|||Perpetuum Mobile",
  "Marie Celeste\t\"album\": \"And Then Perhaps\"",
  "Mario Molino, Lorenzo Patuelli, 2+2 di Nora Orlandi|||Gli angeli del 2000 (Original Soundtrack)",
  "Mark-Almond|||Other Peoples Rooms",
  "Marlena Shaw|||From The Depths Of My Soul",
  "Martinha|||Amigos y Amantes",
  "Martinha|||Martinha",
  "Martinha|||Martinha (1978)",
  "Mary Lou Williams|||Mary Lou Williams",
  "Mary Margaret O'Hara|||Miss America",
  "Masabumi Kikuchi|||Hanamichi",
  "Mason Lindahl|||Kissing Rosy in the Rain",
  "Massimo Catalano, Remigio Ducros|||Idee",
  "Master Wilburn Burchette\t\"album\": \"Opens the Seven Gates of Transcendental Consciousness\"",
  "Mathilde Santing\t\"album\": \"To Others to One\"",
  "Matthew Larkin Cassell|||Pieces",
  "Maxayn|||Reloaded",
  "Mejiwahn, Daniel Bitrán|||Lúil Ó Fadó",
  "Mejiwahn, Liv.e|||Beanna",
  "Mejiwahn, hrlum|||Beanna",
  "Mejiwahn, lojii, Zeroh|||Beanna",
  "Mel Tormé|||A Time For Us",
  "Menahan Street Band\t\"album\": \"Make the Road By Walking\"",
  "Menahan Street Band|||The Exciting Sounds of Menahan Street Band",
  "Messengers Incorporated|||Soulful Proclamation",
  "Michel Colombier|||Colossus: The Forbin Project (Original Motion Picture Soundtrack)",
  "Michel Jonasz|||La nouvelle vie",
  "Michel Legrand\t\"album\": \"Legrand cinéma\"",
  "Michel Legrand|||Michel Legrand chante les moulins de mon coeur",
  "Michel Legrand|||The Music of Michel Legrand",
  "Mike James Kirkland|||Hang on in There",
  "Mike Nock Quartet|||In Out and Around",
  "Mike Posner|||Keep Going",
  "Mike Westbrook Concert Band|||Mike Westbrook's Love Songs",
  "Miles Davis\t\"album\": \"Kind Of Blue (Legacy Edition)\"",
  "Millie Jackson\t\"album\": \"Still Caught Up\"",
  "Millie Jackson\t\"album\": \"The Moods of Millie Jackson: Her Best Ballads\"",
  "Milo, Self Jupiter|||who told you to think​?​?​!​!​?​!​?​!​?​!",
  "Milo|||budding ornithologists are weary of tired analogies",
  "Milt Ward And Virgo Spectrum|||Milt Ward & Virgo Spectrum",
  "Milton Nascimento|||Clube Da Esquina",
  "Milton Nascimento|||Courage",
  "Minako Yoshida|||吉田美奈子 ゴールデン☆ベスト",
  "Mina|||Studio Uno '66",
  "Misha Panfilov\t\"album\": \"On The Hook\"",
  "Mk.gee|||Lonely Fight",
  "Mobb Deep, Nas|||Infinite",
  "Molly Lewis|||The Forgotten Edge",
  "Momoko Gill\t\"album\": \"Momoko\"",
  "Monguito Santamaria\t\"album\": \"Blackout\"",
  "Morelenbaum² / Sakamoto|||Casa",
  "Morgana King|||It's A Quiet Thing",
  "Morton Feldman, Eberhard Blum, Nils Vigeland, Jan Williams|||Morton Feldman: Why Patterns? / Crippled Symmetry",
  "Mother Lion|||I'm The Fool",
  "Mouloudji\t\"album\": \"Comme un p'tit coquelicot\"",
  "Mouloudji|||L'amour, l'amour, l'amour - Le meilleur de Mouloudji",
  "Music Emporium|||Music Emporium",
  "NMW, Zayyy2x, SODA|||The World Through A Looking Glass",
  "Nada\t\"album\": \"Nada\"",
  "Nada|||Ho scoperto che esisto anch'io",
  "Nana Caymmi\t\"album\": \"Retratos\"",
  "Nara Leão|||Nara",
  "Narassa|||Tensione Dinamica",
  "Nat Adderley Sextet|||In The Bag",
  "Navy Blue\t\"album\": \"Memoirs In Armour\"",
  "Navy Blue|||The Sword & The Soaring",
  "Neil Richardson|||Kpm 1000 Series: Open Air",
  "Nektar|||A Tab In The Ocean",
  "Neymar Dias, Agenor de Lorenzi, Igor Pimenta, Gabriel Alterio|||Minhas Cancões Instrumentais",
  "Nick Ingman, De Wolfe Music|||Wide Open Spaces",
  "Nico Fidenco|||La Ragazzina (Original Motion Picture Soundtrack)",
  "Nicola Conte|||Jet Sounds",
  "Nicolette Larson|||In The Nick Of Time",
  "Nina Simone|||Wild Is The Wind",
  "Niningashi\t\"album\": \"Heavy Way\"",
  "Niobe|||Voodooluba",
  "Niontay|||Dontay's Inferno",
  "Novi Singers|||Five, Four, Three",
  "Novi Singers|||Rien ne va plus",
  "Nydia Caro\t\"album\": \"Nydia Caro (Remasterizado 2023)\"",
  "Nydia Caro|||Hoy Canto Por Cantar (Remasterizado 2023)",
  "Nydia Caro|||Nydia Caro (Remasterizado 2023)",
  "OHMA|||Between All Things",
  "OkoNski\t\"album\": \"Entrance Music\"",
  "OkoNski\t\"album\": \"Magnolia\"",
  "OkoNski\t\"album\": \"Trio Session Demos\"",
  "Okonski|||Entrance Music",
  "Okonski|||Magnolia",
  "Ol' Burger Beats\t\"album\": \"Dialogue.\"",
  "Ol' Burger Beats, Vuyo|||All Yours",
  "Ol' Burger Beats|||Out of Sight, Out of Mind",
  "Ol' Burger Beats|||Unreleased Instrumentals",
  "Olivia Newton-John|||Come On Over",
  "Olli Ahvenlahti|||The Poet",
  "Onuma Singsiri|||All I See Is You (Original Soundtrack Album)",
  "Orquestra e Coro Som Livre|||O Semideus",
  "Osvn|||TWOU NWA",
  "Out Of Focus|||Wake Up",
  "Ozy of Oz|||Dreams",
  "Ozzy Osbourne|||The Essential Ozzy Osbourne",
  "Pages\t\"album\": \"Future Street\"",
  "Pale Jay, Okonski|||Bewilderment",
  "Pale Jay|||The Celestial Suite",
  "Paolo Ormi e la sua orchestra|||P.O.X. Sound",
  "Paris Paloma|||labour",
  "Paul McCartney|||Good Evening New York City",
  "Percy Faith & His Orchestra & Chorus|||Love Theme from 'Romeo & Juliet'",
  "Perigeo|||Abbiamo Tutti Un Blues Da Piangere",
  "Pete Dello and Friends|||Into Your Ears",
  "Pete La Roca|||Basra (Remastered)",
  "Peter Thomas Sound Orchester\t\"album\": \"Van De Velde: Die Vollkommene Ehe & Das Leben Zu Zweit\"",
  "Peter Thomas Sound Orchester|||Van De Velde: Die Vollkommene Ehe & Das Leben Zu Zweit",
  "Phil Manzanera, Quiet Sun|||Mainstream",
  "Philippe Besombes|||Libra (Un film du groupe Pattern)",
  "Philippe Sarde\t\"album\": \"Hellé (Original Motion Picture Soundtrack)\"",
  "Philippe Sarde|||Cesar et Rosalie (Original Motion Picture Soundtrack)",
  "Philippe Sarde|||Les Choses De La Vie (Original Motion Picture Soundtrack)",
  "Piero Piccioni\t\"album\": \"Quelle strane occasioni\"",
  "Piero Umiliani\t\"album\": \"La consolazione della pietra\"",
  "Piero Umiliani\t\"album\": \"La ragazza fuori strada\"",
  "Piero Umiliani|||Psichedelica",
  "Piero Umiliani|||Raptus (Original Soundtrack)",
  "Piero Umiliani|||Svezia, Inferno E Paradiso (Outtakes)",
  "Piero Umiliani|||Temi descrittivi per piccolo complesso",
  "Pink Siifu, Armand Hammer|||ONYX’!",
  "Pink Siifu|||ONYX’!",
  "Polish Radio Orchestra|||Lift Off! With Apollo Sound",
  "Preservation, Mach-Hommy|||Eastern Medicine, Western Illness",
  "Prince Phillip Mitchell\t\"album\": \"Top Of The Line (Remastered & Expanded)\"",
  "Pulsar|||Pollen",
  "Quelle Chris\t\"album\": \"Deathfame\"",
  "RYUSENKEI, HITOMITOI|||Talio",
  "RadixTheRuler|||Lawrence (interlude)",
  "Ragnarök|||Ragnarök",
  "Raimonds Pauls, Viktors Lapčenoks|||Jūras Balss",
  "Rare Earth|||Get Ready",
  "Ras G|||Raw Fruit Vol. 5 & 6",
  "Ray Conniff, The Ray Conniff Singers|||I Can See Clearly Now",
  "Ray Conniff|||I'd Like To Teach The World To Sing",
  "Ray Conniff|||The Way We Were",
  "Ray Vaughn, Isaiah Rashad|||EAST CHATT (feat. Isaiah Rashad)",
  "Remigio Ducros|||Misticismo",
  "Resavoir, Matt Gold|||Canopy",
  "Resavoir|||Resavoir",
  "Rita Reys\t\"album\": \"1953, Vol. 2 'Modern Sounds'\"",
  "Riz Ortolani, Katyna Ranieri|||Addio zio Tom (Original Motion Picture Soundtrack) [Remastered]",
  "Riz Ortolani|||Confessione di un commissario di polizia al procuratore della Repubblica (Original Motion Picture Soundtrack) [Remastered]",
  "Robert Genco|||Beyond The Life",
  "Robert Maxwell\t\"album\": \"Shangri-La\"",
  "Robert Maxwell|||Spectacular Harps",
  "Roc Marciano\t\"album\": \"The Elephant Man's Bones\"",
  "Rodolfo Alchourrón, Sanata y Clarificación|||La Historia de un Hombre (Sanata y Clarificación Volumen 3)",
  "Rodolfo Alchourrón|||Sanata y Clarificación Vol. 1 y 2",
  "Roger Webb, De Wolfe Music|||Vocal Patterns",
  "Ronald Langestraat|||Apollo",
  "Ronald Langestraat|||Searching",
  "Ronald Snijders\t\"album\": \"The Nelson & Djosa Sessions\"",
  "Ronald Snijders|||Natural Sources",
  "Ronnie Boykins|||The Will Come, Is Now",
  "Ronnie Laws\t\"album\": \"Pressure Sensitive\"",
  "Rosie Lowe\t\"album\": \"Son\"",
  "Rosie Lowe, Duval Timothy|||Son",
  "Rosinha De Valença|||Um Violão em Primeiro Plano",
  "Royal Philharmonic Pops Orchestra, Henry Mancini|||Premier Pops",
  "Russ Garcia & His Vocal Choir and Orchestra|||Sounds in the Night (2014 - Remaster)",
  "Ruy Maurity|||Fogo Sobre Terra",
  "Ryshon Jones, Moo Latte|||LOOSE STRINGS",
  "Ryuichi Sakamoto, Jaques Morelenbaum, Everton Nelson|||1996",
  "Ryuichi Sakamoto|||Playing The Piano",
  "SBB|||Nowy horyzont",
  "SHOLTO|||Letting Go of Forever",
  "STELLA LEFTY|||Kiss Me",
  "SUBSTANCE810\t\"album\": \"The Lion's Share\"",
  "SUBSTANCE810, Observe Since 98, Asun Eastwood, DJ Grazzhoppa|||The Lion's Share",
  "Sam Dees|||The Show Must Go On",
  "Sam Gendel, Sam Wilkes|||Music for Saxofone & Bass Guitar",
  "Sam Most, Kenny Barron, George Mraz, Walter Bolden, Warren Smith|||From the Attic of My Mind",
  "Sam Well|||I Need",
  "Sam Wilkes, Craig Weinrib, Dylan Day|||Sam Wilkes, Craig Weinrib, and Dylan Day",
  "Samla Mammas Manna|||Samla Mammas Manna",
  "Samuel Jonathan Johnson\t\"album\": \"My Music\"",
  "Samurai|||Samurai (Expanded & Remastered Edition)",
  "Sancho, GRYN, Ally Dee|||SOLAR",
  "Sancho, GRYN|||SOLAR",
  "Sandro Brugnolini|||Overground",
  "Sandy Denny|||Like An Old Fashioned Waltz (Deluxe Edition)",
  "Saori Yuki|||あなたと夜と音楽と -由紀さおりの魅力-",
  "Sarah Vaughan\t\"album\": \"Brownie: The Complete EmArcy Recordings Of Clifford Brown\"",
  "Satomimagae, duenn|||境界 KYOKAI",
  "Satomimagae|||Hanazono",
  "Scallops Hotel|||Plain Speaking",
  "Scarlet Rivera|||Scarlet Rivera",
  "Scott Roewe|||I Dream",
  "Sebastiao Tapajós, Pedro Dos Santos|||Sebastião Tapajos & Pedro Dos Santos",
  "September|||Zadnja avantura",
  "Serú Girán\t\"album\": \"Peperina\"",
  "Sessa|||Estrela Acesa",
  "Sestetto Dino Piana & Oscar Valdambrini|||10 situazioni",
  "Shabaka|||Afrikan Culture",
  "Sharon Forrester|||Show Some Love For Reggae",
  "Shaun Cassidy|||Room Service",
  "Shawn Phillips|||Bright White",
  "Shin Joong Hyun|||Shin Joong Hyun & Yup Juns",
  "Shira Small|||The Line Of Time And The Plane Of Now",
  "Shirley Bassey|||This Is My Life",
  "Shirley Horn|||Here's To Life",
  "Shirley Horn|||May The Music Never End",
  "SiR, Kadhja Bonet|||Chasing Summer",
  "Side Effect|||Portraits",
  "Sidney Joe Qualls|||I Enjoy Loving You",
  "Silvana Di Lorenzo|||Silvana Di Lorenzo",
  "Silvinha\t\"album\": \"Grita Coração\"",
  "Silvinha, Sylvinha Araujo|||Silvinha (1978)",
  "Simon Mavin|||Some Days",
  "Sivuca|||Sivuca",
  "Skaldowie|||Krywań, Krywań",
  "SmooVth, JD Era, Fredro Starr|||Project Near You",
  "Solisti e Orchestre del Cinema Italiano|||Ennio Morricone - Rest of the West - Spaghetti Westerns - Critic's Choice",
  "Som Imaginario|||Matança Do Porco",
  "Sparklmami, William Corduroy, Eddie Burns|||summer school radio with Lovie",
  "Spice|||Let There Be Spice (Digitally Remastered)",
  "Spirale|||Spirale",
  "Stack Moolah\t\"album\": \"Hard 2 Obtain\"",
  "Stan Tracey|||Kpm 1000 Series: Dramatic Background",
  "Stanley Myers\t\"album\": \"Images\"",
  "Stark Reality|||Acting, Thinking, Feeling",
  "Stark Reality|||The Stark Reality Discovers Hoagy Carmichael's Music Shop (Master Tape Transfer)",
  "Stefano Marcucci|||Tempo di demoni, Papi, angioli, incensi e cilici",
  "Stefano Torossi|||Tensione e distensione",
  "Stelvio Cipriani|||Paradiso blu (Original Motion Picture Soundtrack)",
  "Steve Kuhn|||Trance",
  "Stoic, Reyan, Deante' Hitchcock|||DUMMY",
  "Stringtronics|||Tropicola",
  "Studio G|||Nature's World",
  "Sui Generis\t\"album\": \"Pequenas Anécdotas Sobre Las Instituciones\"",
  "Sui Generis|||Confesiones De Invierno",
  "Susannah McCorkle|||Sabia",
  "Sven Libaek\t\"album\": \"Nature Walkabout (Original Television Soundtrack) [Remastered]\"",
  "Sven Wunder|||Daybreak",
  "T2|||It'll All Work Out In Boomland",
  "Takashi Nishioka|||満員の木",
  "Tamba 4|||Samba Blim",
  "Teddy Lasry|||Tutti Fluti",
  "Teena Marie\t\"album\": \"It Must Be Magic (Remastered 2002 / Expanded Edition)\"",
  "Teller Bank$, Ed Glorious|||The Pride & Glory",
  "Teri DeSario\t\"album\": \"Casablanca Records Greatest Hits\"",
  "Terry Huff, Special Delivery|||The Lonely One",
  "Tha God Fahim\t\"album\": \"Iron Bull\"",
  "Tha God Fahim\t\"album\": \"Wide Berth\"",
  "The 3 Pieces|||Vibes Of Truth",
  "The Alchemist, Curren$y|||Flying High, Part 2",
  "The Avalanches, Rivers Cuomo, Pink Siifu|||We Will Always Love You",
  "The Bayan Mongol Variety Group|||The Bayan Mongol Variety Group",
  "The Carpenters\t\"album\": \"Close To You\"",
  "The Chitinous Ensemble|||Chitinous (Remastered)",
  "The Chocolate Watchband|||Inner Mystique",
  "The Circling Sun|||Orbits (Deluxe Version)",
  "The Cleaners From Venus|||Blow Away Your Troubles",
  "The Counts|||It's What's in the Groove",
  "The Dave Brubeck Quartet|||Jazz Goes To College",
  "The Delfonics|||The Sound Of Sexy Soul",
  "The Dining Rooms|||Sensibili alle foglie (The Lost Soundtrack)",
  "The Dynamic Superiors\t\"album\": \"The Dynamic Superiors\"",
  "The Edge Of Daybreak|||Eyes of Love",
  "The Electric Prunes|||Release Of An Oath",
  "The Equatics|||Doin It!!!!",
  "The Ethics|||Now Is the Time",
  "The Family Circle|||Family Circle",
  "The Five Stairsteps, Cubie Burke|||Our Family Portrait",
  "The Giver Of Illness, Ak'chamel|||The Totemist",
  "The Grodeck Whipperjenny|||The Grodeck Whipperjenny",
  "The Howard Lemon Singers|||I Am Determined",
  "The Kimba Unit\t\"album\": \"Tezeta\"",
  "The Lyman Woodard Organization|||Saturday Night Special",
  "The Mighty Mocambos|||A Higher Frequency",
  "The Montclairs, Phil Perry|||Dreaming Out Of Season",
  "The Montclairs|||All I Really Care About (Is You)",
  "The Natural Four|||The Natural Four",
  "The New Birth|||Ain't No Big Thing, But It's Growing",
  "The New Jazz Orchestra|||Le Déjeuner Sur L'Herbe (Remastered 2020)",
  "The Offline\t\"album\": \"Pour Nael\"",
  "The Offline|||The Offline in Session",
  "The Pawnshop|||The Pawnshop",
  "The Ray Conniff Singers|||I Love How You Love Me",
  "The Ray Conniff Singers|||Jean",
  "The Soul Searchers\t\"album\": \"We the People\"",
  "The Temprees|||Love Maze",
  "The Topics|||Giving Up (Digitally Remastered)",
  "The Ultimates|||You're My Lady (Digitally Remastered)",
  "The Undisputed Truth|||The Law Of The Land (Expanded Edition)",
  "The Whispers|||Bingo: The Janus Recordings 1972-1974",
  "The Zenmenn, John Moods|||Hidden Gem",
  "Thee Sacred Souls|||Got a Story to Tell",
  "Thee Sacred Souls|||Will I See You Again?",
  "Tian Niu|||Ayo Ke Disco: Boogie, Pop & Funk from the South China Sea (1974-88)",
  "Tim Maia|||Racional (Vol 1)",
  "Tony Bennett\t\"album\": \"The Columbia Singles, Vol. 2\"",
  "Tony Bennett\t\"album\": \"The Columbia Singles, Vol. 3\"",
  "Tony Bennett|||Tony Bennett's \"\"Something\"",
  "Tony Iglio|||Drugstore",
  "Toshiko Akiyoshi|||Keys of Expression",
  "Toshiyuki Honda|||イージー・ブリージング",
  "Townes Van Zandt\t\"album\": \"Roadsongs\"",
  "Trin-I-Tee 5:7|||Trin-i-tee 5:7",
  "Trio Mocotó\t\"album\": \"Trio Mocoto\"",
  "Trio Ternura|||Série Samba Soul",
  "Trussel|||Love Injection",
  "Tsu Surf, Benny The Butcher|||MSYKM",
  "Tuca|||Meu Eu",
  "U.S. Girls|||Running Errands",
  "Unnatural Funk Band|||Strange Happenings b/w Living In The Past",
  "Vainica Doble|||Heliotropo",
  "Valerie Simpson|||Exposed",
  "Van Der Graaf Generator\t\"album\": \"H To He Who Am The Only One\"",
  "Vanusa|||Amigos Novos e Antigos",
  "Vanusa|||Vanusa",
  "Vanusa|||Vanusa 30 Anos",
  "Vanusa|||Viva Vanusa",
  "Velly Joonas|||Stopp, Seisku Aeg! / Käes On Aeg (7\"\" Version)",
  "Venna\t\"album\": \"Sicily' Box\"",
  "Vladimir Cosma\t\"album\": \"Le grand blond avec une chaussure noire (Bande originale du film d'Yves Robert)\"",
  "Vladimir Cosma|||Sam et Sally (Bande originale de la série télévisé)",
  "Wagner Tiso\t\"album\": \"Trem Mineiro\"",
  "Wagner Tiso|||Assim Seja",
  "Waltel Branco|||Meu Balanço",
  "Wanda Warska|||Piosenki z piwnicy Wandy Warskiej",
  "Wax Machine|||Hermit's Grove",
  "Web Web, Max Herre, Roberto Di Gioia, Brandee Younger|||WEB MAX",
  "Weldon Irvine\t\"album\": \"The Sisters\"",
  "Wendy & Bonnie|||Genesis",
  "Wes Montgomery Trio|||The Wes Montgomery Trio (Expanded Edition)",
  "Westside Gunn\t\"album\": \"Pray for Paris\"",
  "Westside Gunn, Curren$y, Benny The Butcher|||Hitler Wears Hermes 7",
  "Will Hill , Hollywood Cole|||You Should Know",
  "William S. Fischer|||Akelarre sorta bat",
  "Willie Bobo|||A New Dimension",
  "Willie Hutch|||The Mack - Original Motion Picture Soundtrack",
  "Woo|||Which Ever Way",
  "Wrongonyou|||Killer",
  "Włodzimierz Nahorny|||Jej portret",
  "Y. Jasper|||Snowman",
  "Y. Jasper|||Sobriety",
  "YUNGMORPHEUS\t\"album\": \"Thumbing Thru Foliage\"",
  "YUNGMORPHEUS, Goya Gumbani|||Burnished Sums",
  "Yosui Inoue|||断絶 (Remastered 2018)",
  "Your friend daao|||Diary I",
  "Yussef Dayes|||Black Classical Music",
  "Yussef Dayes|||The Yussef Dayes Experience Live at Joshua Tree (Presented by Soulection)",
  "Zagrebački Jazz Kvartet|||40 Godina Zagrebački Jazz Kvartet",
  "Zbigniew Namysłowski, Zbigniew Namysłowski Quintet|||Kujaviak Goes Funky (Polish Jazz vol. 46)",
  "Ze Rodrix|||Soy Latino Americano",
  "ZekeUltra\t\"album\": \"Babel Tower\"",
  "Zelooperz, Real Bad Man, The Alchemist|||Dear Psilocybin",
  "cktrl|||spirit",
  "corto.alto\t\"album\": \"Not for Now\"",
  "gong\t\"album\": \"Angel's Egg (Deluxe Edition)\"",
  "kass|||MI ALMA ES TUYA",
  "Алексей Зубов, Инструментальный ансамбль «Мелодия»|||Ваши любимые песни играет ансамбль \"\"Мелодия\"",
  "Борис Фрумкин, Инструментальный ансамбль «Мелодия»|||Ваши любимые песни играет ансамбль \"\"Мелодия\"",
  "Владимир Чижик, Инструментальный ансамбль «Мелодия»|||Ваши любимые песни играет ансамбль \"\"Мелодия\"",
  "Инструментальный ансамбль «Мелодия»|||Ваши любимые песни играет ансамбль \"\"Мелодия\"",
  "Маргрета Николова, Естраден Оркестър На Комитета За Телевизия И Радио, Вили Казасян|||Маргрета Николова",
  "СОЮЗ, Sessa|||Force of the Wind",
  "СОЮЗ|||II (Remastered)",
  "上田力とパワー・ステーション|||Bos & Boz",
  "五つの赤い風船|||MONUMENT　五つの赤い風船ベストアルバム",
  "屋良ファミリーズ|||Ryukyu Rare Groove Revisited - Okinawa Pops 1957-1978 -",
  "杉本喜代志|||Our Time",
  "横田年昭とビート・ジェネレーション|||フルート・アドヴェンチュアー 太陽はまだ暑く燃えていた…",
  "渥美マリ|||夜のためいき+6",
  "玉木宏樹, S・M・T|||Time Paradox",
  "芸能山城組|||GEINOH YAMASHIROGUMI Live - \"\"Hirakareta Gassho\"\" Junen no Tenkai",
  "芸能山城組|||Shonentachi eno Chikyusanka",
  "菊池ひみこ, アーニー・ワッツ|||DON’T BE STUPID",
  "野口文|||藤子",
  "高橋ユキヒロ|||サラヴァ!"
]);
const SEED_ARTISTS = [
  "1001 Est Crémazie",
  "1619 Bad Ass Band",
  "24 Carat Black",
  "A Song For You, Holan",
  "ABC, Halina Frackowiak",
  "AJ McQueen, Londrelle",
  "Aaron Frazer",
  "Adrian Younge",
  "Airto Moreira",
  "Akira Ishikawa & Count Buffaloes",
  "Aktuala",
  "Al Stewart",
  "Alain Bellaïche",
  "Alain Goraguer",
  "Alan Lorber Orchestra",
  "Alan Parker",
  "Alejandro Jodorowsky",
  "Alessandro Alessandroni",
  "Alessandro Blonksteiner",
  "Alfonso Zenga, Paolo Gatti",
  "Alfred Newman",
  "Alice Coltrane",
  "Allan Holdsworth",
  "Allan Wachs",
  "Alquin",
  "Amado Maita",
  "Amanda Whiting, Chip Wickham",
  "Anacole Daalderop, Marc Eric Laine",
  "Anaïs Mitchell",
  "Andrae Crouch, Disciples",
  "Andre Kostelanetz & His Orchestra",
  "Andre Tschaskowski",
  "Andrew Hill",
  "André Popp",
  "Andy Williams",
  "Angel 'Pocho' Gatti Orchestra",
  "Angel Pocho Gatti e la sua grande orchestra",
  "Angela Bofill",
  "Antonio Adolfo",
  "Antony and the Johnsons, ANOHNI",
  "Antón García Abril",
  "Apollo Brown, Bronze Nazareth",
  "Aquarian Dream",
  "Ara Tokatlian, Milcho Leviev",
  "Arco Iris",
  "Areski Belkacem",
  "Armand Hammer, The Alchemist, billy woods, E L U C I D, Silka, Cleo Reed",
  "Armando Trovajoli",
  "Ash Ra Tempel, Manuel Göttsching",
  "Astrud Gilberto",
  "Augusto Martelli",
  "Azymuth",
  "BADBADNOTGOOD, Charlotte Day Wilson",
  "Balla Et Ses Balladins",
  "Bastien Keb, Claudia Kane",
  "Bemibem",
  "Bengt Hallberg",
  "Benjamim Taubkin",
  "Benny The Butcher, Black Thought",
  "Betty Missiego",
  "Beverly Glenn-Copeland",
  "Big Band Katowice",
  "Bill Evans",
  "Bill Evans Trio",
  "Bill Fay",
  "Billy Strayhorn",
  "Bits & Noise",
  "Bizarrap, Quevedo",
  "Bjørn Alterhaug",
  "Black Savage",
  "Black Thought",
  "Blu, August Fanon, Wyldeflowher, Geminelle, YaH-Ra, Lexus, Noveliss",
  "Blu, YaH-Ra, MED, Thurz",
  "Blue Earth Sound",
  "BlueskyBeatz",
  "Bobby Hutcherson",
  "Bohemian Vendetta",
  "Boillat Thérace Quintet, Benny Bailey",
  "Bonnie Raitt",
  "Brandon Coleman",
  "Bread",
  "Brief Encounter",
  "Broadcast",
  "Brodowski String Quartet & Dave Kane & Marius Neset & Olavi Louhivuori & Dave Stapleton",
  "Bruce Campbell",
  "Bruno Battisti D'Amario",
  "Bruno Nicolai",
  "Burt Bacharach",
  "Butch Dawson",
  "Cal Tjader",
  "Calvin Keys",
  "Caravan",
  "Carca",
  "Cassiano",
  "Catalyst",
  "Caterina Valente",
  "Catherine Howe",
  "Catherine McKinnon",
  "Cecilia",
  "Cesar Camargo Mariano",
  "Cesare Andrea Bixio, Luciano Pavarotti, Andrea Griminelli, Henry Mancini",
  "Charles Lloyd",
  "Charly García",
  "Chassol",
  "Chester Watson",
  "Chester Watson, Dr. Josephine OlaTomi Soboyejo",
  "Chet Baker Quartet, Russ Freeman",
  "Chico Hamilton",
  "Chief Adjuah",
  "Ciccada",
  "Clare Fischer",
  "Claudette Soares",
  "Claudine Longet",
  "Clearlight",
  "Clever Austin",
  "Clipse",
  "Clipse, COLORS",
  "Clipse, Pusha T, Malice",
  "Collettivo Immaginario, Maylee Todd, Tommaso Cappellato, Alberto Lincetto, Nicolò Masetto",
  "Corey Bernhard",
  "Cos",
  "Courtial With Errol Knowles",
  "Cozy Fr",
  "Cynthia Schloss",
  "Céline Dessberg",
  "DJ Gruff",
  "DJ Shocca, Madbuddy",
  "Dan Fogelberg",
  "Danger Mouse, Black Thought, MF DOOM",
  "Daniele Patucchi, Nora Orlandi",
  "Daniele Patucchi, Nora Orlandi, 4 + 4 Di Nora Orlandi",
  "Danny O'Keefe",
  "Dave Bixby",
  "David Axelrod",
  "David Lindup",
  "David Sanborn",
  "Daylan Gideon",
  "Deitrich Johnson",
  "Del Jones' Postive Vibes",
  "Deodato",
  "Di Melo",
  "Dirty Art Club",
  "Diz",
  "Dolly Parton",
  "Dom Salvador, Edison Machado",
  "Dominique Guiot",
  "Don Beto",
  "Don beto",
  "Donald Byrd",
  "Doris Monteiro",
  "Doug Hammond, David Durrah",
  "Doug Lucas",
  "Dough Networkz, Young Roddy, Jameel Na'im X, King Akeem",
  "Dr. Lonnie Smith",
  "Dr. Samuel J. Hoffman",
  "Dr. Yen Lo",
  "Duke Pearson",
  "Durand Jones & The Indications",
  "Dzamble",
  "East Of Eden",
  "Eddy Senay",
  "Eduardo Mateo, Jorge Trasante",
  "Egberto Gismonti",
  "Elis Regina",
  "Eloy",
  "Elton John",
  "Eminem, DMX, Obie Trice",
  "Eminencee",
  "Emma-Jean Thackray",
  "Ennio Morricone",
  "Ennio Morricone e i Cantori Moderni di Alessandroni",
  "Ennio Morricone\\, Edda e i Cantori Moderni di Alessandroni",
  "Enrico Rava",
  "Enrico Rava, Fred Hersch",
  "Enrico Simonetti",
  "Enrico Simonetti, Orquestra Rge",
  "Erick the Architect, Loyle Carner, FARR",
  "Ernan Roch",
  "Erni Clark",
  "Ernie Hines",
  "Ethel Azama",
  "Fabio Frizzi",
  "Fabri Fibra",
  "Fafá de Belém",
  "Fantastic Four",
  "Far East Family Band",
  "Filippo Trecca",
  "Finch",
  "Flako, Miguel Atwood-Ferguson",
  "Floating Points, Pharoah Sanders, London Symphony Orchestra",
  "Focus",
  "Francis Hime",
  "Francis Lai",
  "Francisco Mário",
  "Franco Potenza",
  "Frank McDonald, Chris Rae, De Wolfe Music",
  "Frank Pole, TEO MANDRELLI, Jordan Grace",
  "Françoise Hardy",
  "Freddie Gibbs, The Alchemist",
  "Freundeskreis, Max Herre, Don Philippe, DJ Friction",
  "Fuubutsushi",
  "G3 Victory",
  "GIMS",
  "GIVĒON",
  "GZA, Ghostface Killah, Streetlife",
  "Gabe 'Nandez, Thomas Maggart",
  "Garland Green",
  "Gary Burton",
  "Gene Harris",
  "Gene Harris & The Three Sounds",
  "George Benson",
  "George Otsuka",
  "George Saxon",
  "Gerardo Frisina",
  "Giane",
  "Gianna",
  "Gianni Brezzo",
  "Gianni Brezzo, Simone Alessandrini",
  "Gianni Fallabrino e la sua orchestra",
  "Gianni Ferrio",
  "Gianni Marchetti",
  "Gianni Marchetti, 4 + 4 Di Nora Orlandi",
  "Gilberto Gil",
  "Gilgamesh",
  "Gino Vannelli",
  "Gioielli SEXtet",
  "Gionni Gioielli",
  "Gionni Gioielli, MxRxGxA",
  "Giorgio Gaslini",
  "Glen Campbell",
  "Gloria Ann Taylor",
  "Gotts Street Park",
  "Grover Washington\\, Jr.",
  "Grupa Organowa Krzysztofa Sadowskiego, Krzysztof Sadowski",
  "Guilherme Coutinho, Grupo Stalo",
  "Gustavo Pena - El Príncipe",
  "Guy Skornik",
  "Gwen McCrae",
  "Hadley Caliman",
  "Hailu Mergia, The Walias",
  "Hareton Salvanini",
  "Harold Melvin & The Blue Notes",
  "Harvey Averne",
  "Harvey Mandel",
  "Hatfield & The North",
  "Heitor Villa-Lobos, Norbert Kraft",
  "Hemlata, Ravindra Jain",
  "Henry Mancini",
  "Heraldo Do Monte",
  "Herb Alpert & The Tijuana Brass",
  "Hermeto Pascoal",
  "Hikaru Hayashi",
  "Hoover",
  "Huntertones",
  "I Gres",
  "I Marc 4",
  "IDK, Cordae",
  "Ian Carr",
  "Ike White",
  "Inner Dialogue",
  "Ivan Lins",
  "J Dilla",
  "J.J. Johnson, Bill Withers",
  "JID",
  "JID, Westside Gunn",
  "Jackie Moore",
  "Jackson C. Frank",
  "Jacques Brel, Jean Claudric, Le Grand Orchestre De RTL",
  "Jacula",
  "Jade Warrior",
  "Jameel Na'im X",
  "Jan Akkerman",
  "Jan Jelinek",
  "Jane Olivor",
  "Janko Nilovic",
  "Jasmine Myra",
  "Jason Joshua & The Beholders",
  "Javad Maroufi, Amir Farid",
  "Jean-Luc Ponty",
  "Jean-Pierre Mirouze",
  "Jeff Alexander",
  "Jeff Beck",
  "Jeri Southern",
  "Jerzy Milian, Orkiestra Rozrywkowa PRiTV w Katowicach",
  "Jim Croce",
  "Jimmie D",
  "Joan Brooks",
  "Joe Armon-Jones",
  "Joe Henderson",
  "Joe Sample",
  "Joey Bada$$",
  "John Cameron",
  "John Edwards",
  "John Jacob Niles, Luciano Berio, Cathy Berberian, Juilliard Ensemble",
  "John Lennon",
  "John Stammers",
  "Johnny \"\"Hammond\"\" Smith",
  "Johnny Andrews & The Enjoyments",
  "Johnny Harris",
  "Johnny Lytle",
  "Johnny Mathis",
  "Jonny Teupen",
  "Jordi Sabatés",
  "Jose Mauro",
  "Jose Partida",
  "Joshua, Shablo",
  "José Feliciano",
  "José Luis Perales",
  "João Bosco",
  "João Moraes, Ricardo Santoro",
  "Juan Carlos Calderón, Fernando Lopez",
  "Juarez Moreira",
  "Judee Sill",
  "Judy Collins",
  "Judy Roberts",
  "Julie London",
  "K. L. Saigal",
  "Ka",
  "Kadhja Bonet",
  "Kamaal Williams",
  "Kamaal Williams, Miguel Atwood-Ferguson",
  "Kamasi Washington",
  "Kanye West",
  "Kassi Valazza",
  "Kathryn Moses",
  "Keith Papworth, De Wolfe Music",
  "Kenny Wheeler",
  "Kha'lil",
  "Kid Howl, DDS Pluto",
  "King Curtis",
  "KingiKeem, Dough Networkz",
  "KingiKeem, Dough Networkz, Jameel Na'im X, Wildlifejaydot",
  "KingiKeem, Jameel Na'im X, Ren Gettz",
  "Kit Sebastian",
  "L.N. Chancler, The Chocolate Jam Co.",
  "LIBERATO",
  "La Mont Zeno Theatre",
  "Labi Siffre, Kevin W. Smith",
  "Lallo Gori",
  "Lalo Schifrin",
  "Lani Hall",
  "Larry Nozero, Dennis Tini",
  "Laura Nyro",
  "Laurie Styvers",
  "Lee Hazlewood",
  "Leko, STRAIGHT OUTTA VAULT, Yandhi",
  "Leland Whitty",
  "Les & Larry Elgart",
  "Les McCann",
  "Life",
  "Linda Jones",
  "Lionel Richie",
  "Litto Nebbia",
  "Liv.e",
  "Loaded Honey, Lydia Kitto, J Lloyd",
  "Lolita",
  "Lonnie Liston Smith",
  "Lord Apex",
  "Lord Apex, Dash green",
  "Lorenzo Morresi, Tenderlonious",
  "Los Abuelos De La Nada",
  "Lou Ragland",
  "Lucina",
  "Lucy Steymel",
  "Luis Alberto Spinetta",
  "Luis Bacalov, Ann Margret",
  "Lupita D'Alessio",
  "Luther Ingram",
  "Lynda Dawn",
  "MAVI, Smino",
  "MC Solaar",
  "MIKE, Wiki, The Alchemist",
  "Mach-Hommy",
  "Mach-Hommy, Melanie Charles",
  "Mach-Hommy, Sam Gendel",
  "Maha",
  "Mahavishnu Orchestra",
  "Maki Asakawa",
  "Malcolm Edmonstone Trio",
  "Mano De Santo",
  "Manoella Torres",
  "Manolo Otero",
  "Maranatha! Music",
  "Marcos Valle",
  "Margarita Vilcāne, Nora Bumbiere, Raimonds Pauls",
  "Margie Joseph",
  "Maria Medina",
  "Mariah Carey",
  "Mariani",
  "Marie Celeste",
  "Mario Molino, Lorenzo Patuelli, 2+2 di Nora Orlandi",
  "Mark-Almond",
  "Marlena Shaw",
  "Martinha",
  "Mary Lou Williams",
  "Mary Margaret O'Hara",
  "Masabumi Kikuchi",
  "Mason Lindahl",
  "Massimo Catalano, Remigio Ducros",
  "Master Wilburn Burchette",
  "Mathilde Santing",
  "Matthew Larkin Cassell",
  "Maxayn",
  "Mejiwahn, Daniel Bitrán",
  "Mejiwahn, Liv.e",
  "Mejiwahn, hrlum",
  "Mejiwahn, lojii, Zeroh",
  "Mel Tormé",
  "Menahan Street Band",
  "Messengers Incorporated",
  "Michel Colombier",
  "Michel Jonasz",
  "Michel Legrand",
  "Mike James Kirkland",
  "Mike Nock Quartet",
  "Mike Posner",
  "Mike Westbrook Concert Band",
  "Miles Davis",
  "Millie Jackson",
  "Milo",
  "Milo, Self Jupiter",
  "Milt Ward And Virgo Spectrum",
  "Milton Nascimento",
  "Mina",
  "Minako Yoshida",
  "Misha Panfilov",
  "Mk.gee",
  "Mobb Deep, Nas",
  "Molly Lewis",
  "Momoko Gill",
  "Monguito Santamaria",
  "Morelenbaum² / Sakamoto",
  "Morgana King",
  "Morton Feldman, Eberhard Blum, Nils Vigeland, Jan Williams",
  "Mother Lion",
  "Mouloudji",
  "Music Emporium",
  "NMW, Zayyy2x, SODA",
  "Nada",
  "Nana Caymmi",
  "Nara Leão",
  "Narassa",
  "Nat Adderley Sextet",
  "Navy Blue",
  "Neil Richardson",
  "Nektar",
  "Neymar Dias, Agenor de Lorenzi, Igor Pimenta, Gabriel Alterio",
  "Nick Ingman, De Wolfe Music",
  "Nico Fidenco",
  "Nicola Conte",
  "Nicolette Larson",
  "Nina Simone",
  "Niningashi",
  "Niobe",
  "Niontay",
  "Novi Singers",
  "Nydia Caro",
  "OHMA",
  "OkoNski",
  "Okonski",
  "Ol' Burger Beats",
  "Ol' Burger Beats, Vuyo",
  "Olivia Newton-John",
  "Olli Ahvenlahti",
  "Onuma Singsiri",
  "Orquestra e Coro Som Livre",
  "Osvn",
  "Out Of Focus",
  "Ozy of Oz",
  "Ozzy Osbourne",
  "Pages",
  "Pale Jay",
  "Pale Jay, Okonski",
  "Paolo Ormi e la sua orchestra",
  "Paris Paloma",
  "Paul McCartney",
  "Percy Faith & His Orchestra & Chorus",
  "Perigeo",
  "Pete Dello and Friends",
  "Pete La Roca",
  "Peter Thomas Sound Orchester",
  "Phil Manzanera, Quiet Sun",
  "Philippe Besombes",
  "Philippe Sarde",
  "Piero Piccioni",
  "Piero Umiliani",
  "Pink Siifu",
  "Pink Siifu, Armand Hammer",
  "Polish Radio Orchestra",
  "Preservation, Mach-Hommy",
  "Prince Phillip Mitchell",
  "Pulsar",
  "Quelle Chris",
  "RYUSENKEI, HITOMITOI",
  "RadixTheRuler",
  "Ragnarök",
  "Raimonds Pauls, Viktors Lapčenoks",
  "Rare Earth",
  "Ras G",
  "Ray Conniff",
  "Ray Conniff, The Ray Conniff Singers",
  "Ray Vaughn, Isaiah Rashad",
  "Remigio Ducros",
  "Resavoir",
  "Resavoir, Matt Gold",
  "Rita Reys",
  "Riz Ortolani",
  "Riz Ortolani, Katyna Ranieri",
  "Robert Genco",
  "Robert Maxwell",
  "Roc Marciano",
  "Rodolfo Alchourrón",
  "Rodolfo Alchourrón, Sanata y Clarificación",
  "Roger Webb, De Wolfe Music",
  "Ronald Langestraat",
  "Ronald Snijders",
  "Ronnie Boykins",
  "Ronnie Laws",
  "Rosie Lowe",
  "Rosie Lowe, Duval Timothy",
  "Rosinha De Valença",
  "Royal Philharmonic Pops Orchestra, Henry Mancini",
  "Russ Garcia & His Vocal Choir and Orchestra",
  "Ruy Maurity",
  "Ryshon Jones, Moo Latte",
  "Ryuichi Sakamoto",
  "Ryuichi Sakamoto, Jaques Morelenbaum, Everton Nelson",
  "SBB",
  "SHOLTO",
  "STELLA LEFTY",
  "SUBSTANCE810",
  "SUBSTANCE810, Observe Since 98, Asun Eastwood, DJ Grazzhoppa",
  "Sam Dees",
  "Sam Gendel, Sam Wilkes",
  "Sam Most, Kenny Barron, George Mraz, Walter Bolden, Warren Smith",
  "Sam Well",
  "Sam Wilkes, Craig Weinrib, Dylan Day",
  "Samla Mammas Manna",
  "Samuel Jonathan Johnson",
  "Samurai",
  "Sancho, GRYN",
  "Sancho, GRYN, Ally Dee",
  "Sandro Brugnolini",
  "Sandy Denny",
  "Saori Yuki",
  "Sarah Vaughan",
  "Satomimagae",
  "Satomimagae, duenn",
  "Scallops Hotel",
  "Scarlet Rivera",
  "Scott Roewe",
  "Sebastiao Tapajós, Pedro Dos Santos",
  "September",
  "Serú Girán",
  "Sessa",
  "Sestetto Dino Piana & Oscar Valdambrini",
  "Shabaka",
  "Sharon Forrester",
  "Shaun Cassidy",
  "Shawn Phillips",
  "Shin Joong Hyun",
  "Shira Small",
  "Shirley Bassey",
  "Shirley Horn",
  "SiR, Kadhja Bonet",
  "Side Effect",
  "Sidney Joe Qualls",
  "Silvana Di Lorenzo",
  "Silvinha",
  "Silvinha, Sylvinha Araujo",
  "Simon Mavin",
  "Sivuca",
  "Skaldowie",
  "SmooVth, JD Era, Fredro Starr",
  "Solisti e Orchestre del Cinema Italiano",
  "Som Imaginario",
  "Sparklmami, William Corduroy, Eddie Burns",
  "Spice",
  "Spirale",
  "Stack Moolah",
  "Stan Tracey",
  "Stanley Myers",
  "Stark Reality",
  "Stefano Marcucci",
  "Stefano Torossi",
  "Stelvio Cipriani",
  "Steve Kuhn",
  "Stoic, Reyan, Deante' Hitchcock",
  "Stringtronics",
  "Studio G",
  "Sui Generis",
  "Susannah McCorkle",
  "Sven Libaek",
  "Sven Wunder",
  "T2",
  "Takashi Nishioka",
  "Tamba 4",
  "Teddy Lasry",
  "Teena Marie",
  "Teller Bank$, Ed Glorious",
  "Teri DeSario",
  "Terry Huff, Special Delivery",
  "Tha God Fahim",
  "The 3 Pieces",
  "The Alchemist, Curren$y",
  "The Avalanches, Rivers Cuomo, Pink Siifu",
  "The Bayan Mongol Variety Group",
  "The Carpenters",
  "The Chitinous Ensemble",
  "The Chocolate Watchband",
  "The Circling Sun",
  "The Cleaners From Venus",
  "The Counts",
  "The Dave Brubeck Quartet",
  "The Delfonics",
  "The Dining Rooms",
  "The Dynamic Superiors",
  "The Edge Of Daybreak",
  "The Electric Prunes",
  "The Equatics",
  "The Ethics",
  "The Family Circle",
  "The Five Stairsteps, Cubie Burke",
  "The Giver Of Illness, Ak'chamel",
  "The Grodeck Whipperjenny",
  "The Howard Lemon Singers",
  "The Kimba Unit",
  "The Lyman Woodard Organization",
  "The Mighty Mocambos",
  "The Montclairs",
  "The Montclairs, Phil Perry",
  "The Natural Four",
  "The New Birth",
  "The New Jazz Orchestra",
  "The Offline",
  "The Pawnshop",
  "The Ray Conniff Singers",
  "The Soul Searchers",
  "The Temprees",
  "The Topics",
  "The Ultimates",
  "The Undisputed Truth",
  "The Whispers",
  "The Zenmenn, John Moods",
  "Thee Sacred Souls",
  "Tian Niu",
  "Tim Maia",
  "Tony Bennett",
  "Tony Iglio",
  "Toshiko Akiyoshi",
  "Toshiyuki Honda",
  "Townes Van Zandt",
  "Trin-I-Tee 5:7",
  "Trio Mocotó",
  "Trio Ternura",
  "Trussel",
  "Tsu Surf, Benny The Butcher",
  "Tuca",
  "U.S. Girls",
  "Unnatural Funk Band",
  "Vainica Doble",
  "Valerie Simpson",
  "Van Der Graaf Generator",
  "Vanusa",
  "Velly Joonas",
  "Venna",
  "Vladimir Cosma",
  "Wagner Tiso",
  "Waltel Branco",
  "Wanda Warska",
  "Wax Machine",
  "Web Web, Max Herre, Roberto Di Gioia, Brandee Younger",
  "Weldon Irvine",
  "Wendy & Bonnie",
  "Wes Montgomery Trio",
  "Westside Gunn",
  "Westside Gunn, Curren$y, Benny The Butcher",
  "Will Hill , Hollywood Cole",
  "William S. Fischer",
  "Willie Bobo",
  "Willie Hutch",
  "Woo",
  "Wrongonyou",
  "Włodzimierz Nahorny",
  "Y. Jasper",
  "YUNGMORPHEUS",
  "YUNGMORPHEUS, Goya Gumbani",
  "Yosui Inoue",
  "Your friend daao",
  "Yussef Dayes",
  "Zagrebački Jazz Kvartet",
  "Zbigniew Namysłowski, Zbigniew Namysłowski Quintet",
  "Ze Rodrix",
  "ZekeUltra",
  "Zelooperz, Real Bad Man, The Alchemist",
  "cktrl",
  "corto.alto",
  "gong",
  "kass",
  "Алексей Зубов, Инструментальный ансамбль «Мелодия»",
  "Борис Фрумкин, Инструментальный ансамбль «Мелодия»",
  "Владимир Чижик, Инструментальный ансамбль «Мелодия»",
  "Инструментальный ансамбль «Мелодия»",
  "Маргрета Николова, Естраден Оркестър На Комитета За Телевизия И Радио, Вили Казасян",
  "СОЮЗ",
  "СОЮЗ, Sessa",
  "上田力とパワー・ステーション",
  "五つの赤い風船",
  "屋良ファミリーズ",
  "杉本喜代志",
  "横田年昭とビート・ジェネレーション",
  "渥美マリ",
  "玉木宏樹, S・M・T",
  "芸能山城組",
  "菊池ひみこ, アーニー・ワッツ",
  "野口文",
  "高橋ユキヒロ"
];